services:
  app:
    container_name: invitedex
    build:
      context: .
      dockerfile: dockerfile.local
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/app
    ports:
      - 3000:3000
    networks:
      - invitedex

  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: miniolocal
      MINIO_ROOT_PASSWORD: miniolocal
    volumes:
      - ./.docker/stores/minio:/data
    networks:
      - invitedex
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  invitedex:
    name: invitedex
    driver: bridge
